/* Farmhand's Route - tools, machines, buildings and gear. Source: Stardew Valley Wiki (Tools, Crafting, Carpenter's
   Shop, Buildings, Adventurer's Guild, Rings, Boots pages), 1.6 numbers, checked 2026-09-18.
   cat: Tool, Machine, Building, Weapon, Gear. from: where it comes from. w/h: footprint in tiles (buildings). */
'use strict';

var ITEMS = [
 /* ---------- TOOLS ---------- */
 {name:'Pickaxe',cat:'Tool',from:'Clint',use:'Breaks rocks and nodes; Steel clears the farm boulders and the Dwarf rock',tiers:[
   {name:'Copper',gold:2000,mats:'5 Copper Bar',days:2,fx:'floors 1-39 in one hit'},
   {name:'Steel',gold:5000,mats:'5 Iron Bar',days:2,fx:'floors 40-79 in one hit, farm boulders'},
   {name:'Gold',gold:10000,mats:'5 Gold Bar',days:2,fx:'floors 80-120 in one hit, meteorites'},
   {name:'Iridium',gold:25000,mats:'5 Iridium Bar',days:2,fx:'Skull Cavern rocks in one hit'}],
  note:'Every upgrade takes two days and the tool is gone meanwhile; hand it in after a mine day.'},
 {name:'Axe',cat:'Tool',from:'Clint',use:'Chops trees; Copper clears hardwood stumps, Steel the log into the Secret Woods',tiers:[
   {name:'Copper',gold:2000,mats:'5 Copper Bar',days:2,fx:'large stumps: hardwood'},
   {name:'Steel',gold:5000,mats:'5 Iron Bar',days:2,fx:'large logs: the Secret Woods'},
   {name:'Gold',gold:10000,mats:'5 Gold Bar',days:2,fx:'trees in 4 hits'},
   {name:'Iridium',gold:25000,mats:'5 Iridium Bar',days:2,fx:'trees in 2 hits'}]},
 {name:'Watering Can',cat:'Tool',from:'Clint',use:'Waters crops; hold the button for a line or a square from Copper up',tiers:[
   {name:'Copper',gold:2000,mats:'5 Copper Bar',days:2,fx:'55 charges, 3 in a line'},
   {name:'Steel',gold:5000,mats:'5 Iron Bar',days:2,fx:'70 charges, 5 in a line'},
   {name:'Gold',gold:10000,mats:'5 Gold Bar',days:2,fx:'85 charges, 3 by 3'},
   {name:'Iridium',gold:25000,mats:'5 Iridium Bar',days:2,fx:'100 charges, 6 by 3'}],
  note:'Hand it in the evening before a forecast rain; since 1.6 it comes back full.'},
 {name:'Hoe',cat:'Tool',from:'Clint',use:'Tills soil and digs artifact spots (the wiggling worms)',tiers:[
   {name:'Copper',gold:2000,mats:'5 Copper Bar',days:2,fx:'3 in a line'},
   {name:'Steel',gold:5000,mats:'5 Iron Bar',days:2,fx:'5 in a line'},
   {name:'Gold',gold:10000,mats:'5 Gold Bar',days:2,fx:'3 by 3'},
   {name:'Iridium',gold:25000,mats:'5 Iridium Bar',days:2,fx:'6 by 3'}],
  note:'The last tool worth upgrading in Year 1.'},
 {name:'Scythe',cat:'Tool',from:'Start',use:'Cuts grass into hay (with a Silo), weeds into fiber; harvests Kale, Wheat, Amaranth; costs no energy',note:'The Golden Scythe waits at the end of the Quarry Mine once the Crafts Room bridge is repaired: 75% hay per grass.'},
 {name:'Trash Can',cat:'Tool',from:'Clint',use:'Gives back part of the value of anything you trash',tiers:[
   {name:'Copper',gold:1000,mats:'5 Copper Bar',days:2,fx:'15% back'},
   {name:'Steel',gold:2500,mats:'5 Iron Bar',days:2,fx:'30% back'},
   {name:'Gold',gold:5000,mats:'5 Gold Bar',days:2,fx:'45% back'},
   {name:'Iridium',gold:12500,mats:'5 Iridium Bar',days:2,fx:'60% back'}]},
 {name:'Copper Pan',cat:'Tool',from:'Reward',use:'Pans ore from the glittering spots in rivers and lakes; free from Willy once the Fish Tank room is done',note:'Extra pans cost 2,500g at Willy’s; Clint upgrades it like a tool from 1.6.'},
 {name:'Bamboo Pole',cat:'Tool',from:'Willy',use:'The first rod: no bait, no tackle; free from Willy’s letter on Spring 2',gold:500},
 {name:'Training Rod',cat:'Tool',from:'Willy',gold:25,use:'Big bar, only fish under difficulty 50, always normal quality; a crutch, not a plan'},
 {name:'Fiberglass Rod',cat:'Tool',from:'Willy',gold:1800,unlock:'Fishing 2',use:'Takes bait, so fish bite twice as fast; the first big buy for the fisher'},
 {name:'Iridium Rod',cat:'Tool',from:'Willy',gold:7500,unlock:'Fishing 6',use:'Bait plus one tackle: a Trap Bobber makes the hard bundle fish land'},
 {name:'Backpack',cat:'Tool',from:'Pierre',use:'More inventory: 24 slots, then 36',tiers:[{name:'Large Pack',gold:2000,fx:'24 slots'},{name:'Deluxe Pack',gold:10000,fx:'36 slots'}]},
 {name:'Milk Pail',cat:'Tool',from:'Marnie',gold:1000,use:'Milks cows and goats; buy it with the first cow'},
 {name:'Shears',cat:'Tool',from:'Marnie',gold:1000,use:'Shears sheep; only needed with a Deluxe Barn'},
 {name:'Heater',cat:'Tool',from:'Marnie',gold:2000,use:'Keeps coop or barn animals in a good mood through Winter; one comes from the Fodder bundle'},
 {name:'Auto-Grabber',cat:'Tool',from:'Marnie',gold:25000,unlock:'Farming 10',use:'Collects milk, eggs and wool in one building by itself; Year 2'},

 /* ---------- MACHINES AND CRAFTING ---------- */
 {name:'Chest',cat:'Machine',from:'Craft',mats:'50 Wood',unlock:'known from the start',use:'36 slots; put one by the door and one in the Community Center for bundle items'},
 {name:'Big Chest',cat:'Machine',from:'Craft',mats:'120 Wood, 2 Copper Bar',unlock:'recipe 5,000g at Robin’s',use:'70 slots; drop it onto an old chest to keep the contents',v16:true},
 {name:'Scarecrow',cat:'Machine',from:'Craft',mats:'50 Wood, 1 Coal, 20 Fiber',unlock:'Farming 1',use:'Keeps crows off crops in a circle 8 tiles out (248 tiles)'},
 {name:'Basic Fertilizer',cat:'Machine',from:'Craft',mats:'2 Sap',unlock:'Farming 1',use:'Better odds of silver and gold crops; also Pierre 100g from Spring 15'},
 {name:'Sprinkler',cat:'Machine',from:'Craft',mats:'1 Copper Bar, 1 Iron Bar',unlock:'Farming 2',use:'Waters the 4 tiles beside it every morning; barely worth the bars'},
 {name:'Quality Sprinkler',cat:'Machine',from:'Craft',mats:'1 Iron Bar, 1 Gold Bar, 1 Refined Quartz',unlock:'Farming 6',use:'Waters the 8 tiles around it every morning: the Year 1 workhorse; one comes from the Summer Crops bundle'},
 {name:'Iridium Sprinkler',cat:'Machine',from:'Craft',mats:'1 Gold Bar, 1 Iridium Bar, 1 Battery Pack',unlock:'Farming 9',use:'Waters 24 tiles (5 by 5); Krobus sells one every Friday for 10,000g'},
 {name:'Mayonnaise Machine',cat:'Machine',from:'Craft',mats:'15 Wood, 15 Stone, 1 Earth Crystal, 1 Copper Bar',unlock:'Farming 2',time:'3 hours',makes:'Mayonnaise 190g (Large Egg: gold 285g; Duck Egg: 375g)',use:'Turns a 50g egg into 190g'},
 {name:'Bee House',cat:'Machine',from:'Craft',mats:'40 Wood, 8 Coal, 1 Iron Bar, 1 Maple Syrup',unlock:'Farming 3',time:'4 days',makes:'Honey 100g; Poppy Honey 380g, Fairy Rose Honey 680g with the flower within 5 tiles',use:'Honey every 4 days outdoors, Spring to Fall; an Artisan bundle item'},
 {name:'Speed-Gro',cat:'Machine',from:'Craft',mats:'1 Pine Tar, 5 Moss (makes 5)',unlock:'Farming 3',use:'Crops grow 10% faster; Pierre 100g; 20 come from the Spring Crops bundle',v16:true},
 {name:'Preserves Jar',cat:'Machine',from:'Craft',mats:'50 Wood, 40 Stone, 8 Coal',unlock:'Farming 4',time:'2 to 3 days',makes:'Jelly or Pickles at 2x the input plus 50g',use:'The Year 1 processor: Blueberry 50g becomes Jelly 150g; beats the keg for anything under 50g'},
 {name:'Basic Retaining Soil',cat:'Machine',from:'Craft',mats:'2 Stone',unlock:'Farming 4',use:'A chance the tile stays watered overnight'},
 {name:'Cheese Press',cat:'Machine',from:'Craft',mats:'45 Wood, 45 Stone, 10 Hardwood, 1 Copper Bar',unlock:'Farming 6',time:'3 hours 20 min',makes:'Cheese 230g (Large Milk: gold 345g); Goat Cheese 400g',use:'Milk in, Cheese out; Cheese is an Artisan bundle item and the best mine food'},
 {name:'Loom',cat:'Machine',from:'Craft',mats:'60 Wood, 30 Fiber, 1 Pine Tar',unlock:'Farming 7',time:'4 hours',makes:'Cloth 470g',use:'Wool in, Cloth out; Cloth is an Artisan bundle option'},
 {name:'Keg',cat:'Machine',from:'Craft',mats:'30 Wood, 1 Copper Bar, 1 Iron Bar, 1 Oak Resin',unlock:'Farming 8',time:'Pale Ale 1.5 days, Juice 4 days, Wine 6 days',makes:'Pale Ale 300g from a Hop; Wine at 3x the fruit; Juice at 2.25x the vegetable',use:'The money machine from Fall: hops, pumpkins, starfruit, ancient fruit'},
 {name:'Oil Maker',cat:'Machine',from:'Craft',mats:'50 Slime, 20 Hardwood, 1 Gold Bar',unlock:'Farming 8',time:'6 hours (Truffle)',makes:'Truffle Oil 1,065g; Oil 100g from Corn or Sunflower',use:'Truffles into Truffle Oil; Year 2 with pigs'},
 {name:'Deluxe Speed-Gro',cat:'Machine',from:'Craft',mats:'1 Oak Resin, 5 Bone Fragment (makes 5)',unlock:'Farming 8',use:'Crops grow 25% faster; the Oasis sells it on Thursdays for 80g',v16:true},
 {name:'Seed Maker',cat:'Machine',from:'Craft',mats:'25 Wood, 10 Coal, 1 Gold Bar',unlock:'Farming 9, or the Dye bundle reward',time:'20 minutes',makes:'1 to 3 seeds from one crop',use:'Multiplies Ancient Fruit and strawberries; never sells the last fruit'},
 {name:'Quality Fertilizer',cat:'Machine',from:'Craft',mats:'4 Sap, 1 Fish (makes 2)',unlock:'Farming 9',use:'Good odds of gold crops; Pierre from Year 2; 30 come from the Vault 5,000g bundle',v16:true},
 {name:'Furnace',cat:'Machine',from:'Craft',mats:'20 Copper Ore, 25 Stone',unlock:'Clint visits the morning after your first Copper Ore',time:'Copper 30 min, Iron 2 h, Gold 5 h, Iridium 8 h',makes:'1 bar from 5 ore and 1 Coal; Refined Quartz from Quartz',use:'Every bar starts here: tools, sprinklers, kegs, the Blacksmith’s bundle'},
 {name:'Charcoal Kiln',cat:'Machine',from:'Craft',mats:'20 Wood, 2 Copper Bar',unlock:'Foraging 2',time:'30 minutes',makes:'1 Coal from 10 Wood',use:'Coal without the mines; one comes from the Construction bundle',v16:true},
 {name:'Tapper',cat:'Machine',from:'Craft',mats:'40 Wood, 2 Copper Bar',unlock:'Foraging 4',time:'Maple 9 days, Oak 7, Pine 5',makes:'Maple Syrup 200g, Oak Resin 150g, Pine Tar 100g',use:'On oaks for keg resin, one maple for the Bee House, one pine for the Loom'},
 {name:'Lightning Rod',cat:'Machine',from:'Craft',mats:'1 Iron Bar, 1 Refined Quartz, 5 Bat Wing',unlock:'Foraging 6',makes:'Battery Pack the day after a strike',use:'Catches lightning in storms (Summer 13 and 26 are certain); one comes from the Vault 10,000g bundle'},
 {name:'Cookout Kit',cat:'Machine',from:'Craft',mats:'15 Wood, 10 Fiber, 3 Coal',unlock:'Foraging 3',use:'A one-day kitchen anywhere: cook the Fried Egg and Maki Roll without the house upgrade',v16:true},
 {name:'Field Snack',cat:'Machine',from:'Craft',mats:'1 Acorn, 1 Maple Seed, 1 Pine Cone',unlock:'Foraging 1',use:'45 energy from tree seeds; the miner’s snack with Salmonberries'},
 {name:'Wild Seeds',cat:'Machine',from:'Craft',mats:'one of each forage of the season (makes 10)',unlock:'Foraging 1, 4, 6, 7 by season',use:'Plants the season’s forage as a crop; crows ignore it; the bundle rewards give 30'},
 {name:'Warp Totem: Beach',cat:'Machine',from:'Craft',mats:'1 Hardwood, 2 Coral, 10 Fiber',unlock:'Foraging 6',use:'One-use warp to the beach; 5 come from the Ocean Fish bundle, handy for the night fish'},
 {name:'Warp Totem: Mountains',cat:'Machine',from:'Craft',mats:'1 Hardwood, 1 Iron Bar, 25 Stone',unlock:'Foraging 7',use:'One-use warp to the mountain lake and the mines'},
 {name:'Warp Totem: Farm',cat:'Machine',from:'Craft',mats:'1 Hardwood, 1 Honey, 20 Fiber',unlock:'Foraging 8',use:'One-use warp home; leave the mines at 1:50am'},
 {name:'Rain Totem',cat:'Machine',from:'Craft',mats:'1 Hardwood, 1 Truffle Oil, 5 Pine Tar',unlock:'Foraging 9',use:'Tomorrow rains: the only Winter Walleye; not realistic in Year 1'},
 {name:'Mushroom Log',cat:'Machine',from:'Craft',mats:'10 Hardwood, 10 Moss',unlock:'Foraging 4',time:'every 4 days',makes:'1 to 5 mushrooms from the wild trees around it',use:'Common, Red and Purple Mushrooms at home, all year',v16:true},
 {name:'Cherry Bomb',cat:'Machine',from:'Craft',mats:'4 Copper Ore, 1 Coal',unlock:'Mining 1',use:'Small blast; clears a rock cluster'},
 {name:'Staircase',cat:'Machine',from:'Craft',mats:'99 Stone',unlock:'Mining 2',use:'Drops you one floor instantly; Robin’s stone at 20g makes each about 2,000g'},
 {name:'Transmute (Fe)',cat:'Machine',from:'Craft',mats:'3 Copper Bar',unlock:'Mining 4',makes:'1 Iron Bar',use:'Iron from spare copper'},
 {name:'Glowstone Ring',cat:'Machine',from:'Craft',mats:'5 Solar Essence, 5 Iron Bar',unlock:'Mining 4',use:'Light and magnetism in one ring'},
 {name:'Bomb',cat:'Machine',from:'Craft',mats:'4 Iron Ore, 1 Coal',unlock:'Mining 6',use:'Medium blast; also opens the Dwarf rock'},
 {name:'Transmute (Au)',cat:'Machine',from:'Craft',mats:'2 Iron Bar',unlock:'Mining 7',makes:'1 Gold Bar',use:'Gold from spare iron; cheaper than Clint’s 400g ore'},
 {name:'Mega Bomb',cat:'Machine',from:'Craft',mats:'4 Gold Ore, 1 Solar Essence, 1 Void Essence',unlock:'Mining 8',use:'Big blast for Skull Cavern ore clusters'},
 {name:'Crystalarium',cat:'Machine',from:'Craft',mats:'99 Stone, 5 Gold Bar, 2 Iridium Bar, 1 Battery Pack',unlock:'Mining 9, or the Vault 25,000g bundle',time:'Diamond 5 days, Ruby 2 days',makes:'A copy of any gem forever',use:'Put a Diamond in and never take it out'},
 {name:'Bait',cat:'Machine',from:'Craft',mats:'1 Bug Meat (makes 5)',unlock:'Fishing 2',use:'Fish bite twice as fast; Willy sells it at 5g; crab pots need one a day'},
 {name:'Crab Pot',cat:'Machine',from:'Craft',mats:'40 Wood, 3 Iron Bar',unlock:'Fishing 3',time:'overnight',makes:'Lobster, Crab, Shrimp, Clam in the sea; Crayfish, Snail, Periwinkle in fresh water',use:'Bait it, collect it next morning; Willy sells them at 1,500g; 3 come from the Crab Pot bundle'},
 {name:'Deluxe Bait',cat:'Machine',from:'Craft',mats:'5 Bait, 2 Moss (makes 5)',unlock:'Fishing 4',use:'Faster bites and a bigger bar; 30 come from the River Fish bundle',v16:true},
 {name:'Worm Bin',cat:'Machine',from:'Craft',mats:'15 Hardwood, 1 Gold Bar, 1 Iron Bar, 50 Fiber',unlock:'Fishing 4',time:'daily',makes:'4 to 5 Bait every morning',use:'Free bait for the season',v16:true},
 {name:'Recycling Machine',cat:'Machine',from:'Craft',mats:'25 Wood, 25 Stone, 1 Iron Bar',unlock:'Fishing 4',makes:'Stone, Coal, Iron Ore, Cloth, Refined Quartz from trash',use:'Turns fished-up junk into materials; one comes from the Field Research bundle'},
 {name:'Trap Bobber',cat:'Machine',from:'Craft',mats:'1 Copper Bar, 10 Sap',unlock:'Fishing 6',use:'Tackle: the catch bar drains a third slower; the bundle-fish tackle'},
 {name:'Spinner',cat:'Machine',from:'Craft',mats:'2 Iron Bar',unlock:'Fishing 6',use:'Tackle: faster bites'},
 {name:'Sonar Bobber',cat:'Machine',from:'Craft',mats:'1 Iron Bar, 2 Refined Quartz',unlock:'Fishing 6',use:'Tackle: shows which fish is hooked, so you can let junk go',v16:true},
 {name:'Bait Maker',cat:'Machine',from:'Craft',mats:'3 Iron Bar, 3 Coral, 1 Sea Urchin',unlock:'Fishing 6',time:'10 minutes',makes:'5 to 10 targeted bait from one fish',use:'Bait that makes one kind of fish bite more: a Walleye into Walleye bait',v16:true},
 {name:'Cork Bobber',cat:'Machine',from:'Craft',mats:'10 Wood, 5 Hardwood, 10 Slime',unlock:'Fishing 7',use:'Tackle: a bigger catch bar'},
 {name:'Fish Smoker',cat:'Machine',from:'Craft',mats:'10 Hardwood, 1 River Jelly, 1 Sea Jelly, 1 Cave Jelly',unlock:'recipe 10,000g at Willy’s',time:'50 minutes',makes:'Smoked Fish at double the fish’s price',use:'Doubles every fish for one coal; the fisher’s money machine',v16:true},
 {name:'Dehydrator',cat:'Machine',from:'Craft',mats:'30 Wood, 2 Clay, 1 Fire Quartz',unlock:'recipe 10,000g at Pierre’s',time:'1 day',makes:'Dried Fruit from 5 fruit; Raisins 600g from 5 Grapes',use:'The release valve when the jars are full',v16:true},
 {name:'Life Elixir',cat:'Machine',from:'Craft',mats:'1 Red Mushroom, 1 Purple Mushroom, 1 Morel, 1 Chanterelle',unlock:'Combat 2',use:'Full heal in the mines'},
 {name:'Sturdy Ring',cat:'Machine',from:'Craft',mats:'2 Copper Bar, 25 Bug Meat, 25 Slime',unlock:'Combat 1',use:'Debuffs last half as long'},
 {name:'Wood Fence',cat:'Machine',from:'Craft',mats:'2 Wood',unlock:'known from the start',use:'Keeps animals in and off the crops; rots in a season or two'},
 {name:'Gate',cat:'Machine',from:'Craft',mats:'10 Wood',unlock:'known from the start',use:'A door in a fence line'},
 {name:'Torch',cat:'Machine',from:'Craft',mats:'1 Wood, 2 Sap',unlock:'known from the start',use:'Light; sits on fences and, since 1.6, on sprinklers'},
 {name:'Wood Path',cat:'Machine',from:'Craft',mats:'1 Wood',unlock:'known from the start',use:'A path: faster walking, no debris spawns on it'},
 {name:'Tea Sapling',cat:'Machine',from:'Craft',mats:'2 Wild Seeds, 5 Fiber, 5 Wood',unlock:'Caroline’s 2-heart scene',use:'A bush: Tea Leaves daily in the last week of Spring, Summer and Fall; Green Tea 100g in a keg'},

 /* ---------- BUILDINGS ---------- */
 {name:'Coop',cat:'Building',from:'Robin',gold:4000,mats:'300 Wood, 100 Stone',w:6,h:3,days:3,use:'4 chickens: an egg a day each; the Animal bundle wants a Large Egg and a Large Brown Egg'},
 {name:'Big Coop',cat:'Building',from:'Robin',gold:10000,mats:'400 Wood, 150 Stone',w:6,h:3,days:2,use:'8 animals and an incubator; ducks for the Duck Egg and Duck Feather'},
 {name:'Deluxe Coop',cat:'Building',from:'Robin',gold:20000,mats:'500 Wood, 200 Stone',w:6,h:3,days:2,use:'12 animals, feeds itself; rabbits for Wool and the Rabbit’s Foot'},
 {name:'Barn',cat:'Building',from:'Robin',gold:6000,mats:'350 Wood, 150 Stone',w:7,h:4,days:3,use:'4 cows: milk daily, cheese from Farming 6'},
 {name:'Big Barn',cat:'Building',from:'Robin',gold:12000,mats:'450 Wood, 200 Stone',w:7,h:4,days:2,use:'8 animals; goats for Goat Milk and Goat Cheese'},
 {name:'Deluxe Barn',cat:'Building',from:'Robin',gold:25000,mats:'550 Wood, 300 Stone',w:7,h:4,days:2,use:'12 animals, feeds itself; sheep and pigs (truffles)'},
 {name:'Silo',cat:'Building',from:'Robin',gold:100,mats:'100 Stone, 10 Clay, 5 Copper Bar',w:3,h:3,days:2,use:'240 hay from scythed grass; build it before the first animal'},
 {name:'Well',cat:'Building',from:'Robin',gold:1000,mats:'75 Stone',w:3,h:3,days:2,use:'Refills the watering can; only if the field is far from water'},
 {name:'Shed',cat:'Building',from:'Robin',gold:15000,mats:'300 Wood',w:7,h:3,days:2,use:'An empty room for 67 kegs or jars'},
 {name:'Big Shed',cat:'Building',from:'Robin',gold:20000,mats:'550 Wood, 300 Stone',w:7,h:3,days:2,use:'Upgrade: room for 137 machines'},
 {name:'Stable',cat:'Building',from:'Robin',gold:10000,mats:'100 Hardwood, 5 Iron Bar',w:4,h:2,days:2,use:'A horse: 30% faster everywhere'},
 {name:'Mill',cat:'Building',from:'Robin',gold:2500,mats:'50 Stone, 150 Wood, 4 Cloth',w:4,h:2,days:2,use:'Wheat into flour, beets into sugar overnight'},
 {name:'Fish Pond',cat:'Building',from:'Robin',gold:5000,mats:'200 Stone, 5 Seaweed, 5 Green Algae',w:5,h:5,days:2,use:'One kind of fish breeds and gives roe; the remixed Fish Farmer’s bundle wants 15'},
 {name:'Slime Hutch',cat:'Building',from:'Robin',gold:10000,mats:'500 Stone, 10 Refined Quartz, 1 Iridium Bar',w:7,h:4,days:2,use:'20 slimes for Slime and slime eggs; Year 2',v16:true},
 {name:'Shipping Bin',cat:'Building',from:'Robin',gold:250,mats:'150 Wood',w:2,h:1,days:0,use:'A second bin by the barns; ships overnight like the first'},
 {name:'Cabin',cat:'Building',from:'Robin',gold:100,w:5,h:3,days:0,use:'Player 2’s house: 100g, built on the spot; the starting cabin is free',v16:true},
 {name:'Pet Bowl',cat:'Building',from:'Robin',gold:5000,mats:'25 Hardwood',w:2,h:2,days:0,use:'A second cat or dog',v16:true},
 {name:'House Upgrade 1',cat:'Building',from:'Robin',gold:10000,mats:'450 Wood',nofp:true,days:3,use:'The kitchen: cooking and a fridge (host only)'},
 {name:'House Upgrade 2',cat:'Building',from:'Robin',gold:65000,mats:'100 Hardwood',nofp:true,days:3,use:'Two more rooms; Year 2',v16:true,note:'1.6 raised the price from 50,000g and cut the hardwood from 150.'},
 {name:'Cellar',cat:'Building',from:'Robin',gold:100000,nofp:true,days:3,use:'33 casks for aging wine and cheese; Year 2 or 3'},
 {name:'Greenhouse',cat:'Building',from:'Reward',w:7,h:6,days:0,use:'Any crop, any season, 120 tiles inside plus 18 fruit trees around the edge; the Pantry reward',note:'Exterior 7 by 6 with a 3 by 2 porch; it can be moved at Robin’s.'},
 {name:'Junimo Hut',cat:'Building',from:'Wizard',gold:20000,mats:'200 Stone, 9 Starfruit, 100 Fiber',w:3,h:2,days:0,use:'Three Junimos harvest the 17 by 17 square around it; after the Center is done'},

 /* ---------- WEAPONS ---------- */
 {name:'Rusty Sword',cat:'Weapon',from:'Marlon',use:'Free at the mine entrance on Spring 5; 2 to 5 damage, enough for floors 1 to 20'},
 {name:'Silver Saber',cat:'Weapon',from:'Marlon',gold:750,unlock:'floor 20',use:'8 to 15 damage: the value sword for the frozen floors'},
 {name:'Cutlass',cat:'Weapon',from:'Marlon',gold:1500,unlock:'floor 25',use:'9 to 17 damage'},
 {name:'Templar’s Blade',cat:'Weapon',from:'Marlon',gold:4000,unlock:'floor 55',use:'22 to 29 damage: buy it before floor 80'},
 {name:'Obsidian Edge',cat:'Weapon',from:'Reward',unlock:'chest on floor 90',use:'30 to 45 damage, free; carries the miner to 120 and into the Skull Cavern'},
 {name:'Steel Falchion',cat:'Weapon',from:'Marlon',gold:9000,unlock:'floor 90',use:'28 to 46 damage and fast; the paid alternative to the Obsidian Edge'},
 {name:'Lava Katana',cat:'Weapon',from:'Marlon',gold:25000,unlock:'floor 120',use:'55 to 64 damage: the Skull Cavern sword until the Galaxy Sword'},
 {name:'Slingshot',cat:'Weapon',from:'Reward',unlock:'chest on floor 40',use:'Ranged; Explosive Ammo (300g at the Guild) clears rock clusters'},

 /* ---------- GEAR ---------- */
 {name:'Leather Boots',cat:'Gear',from:'Reward',gold:500,unlock:'chest on floor 10',use:'+1 defence, +1 immunity: the first boots'},
 {name:'Tundra Boots',cat:'Gear',from:'Reward',gold:750,unlock:'chest on floor 50',use:'+2 defence, +1 immunity'},
 {name:'Firewalker Boots',cat:'Gear',from:'Reward',gold:2000,unlock:'chest on floor 80',use:'+3 defence, +3 immunity: wear them from floor 80'},
 {name:'Space Boots',cat:'Gear',from:'Reward',gold:5000,unlock:'chest on floor 110',use:'+4 defence, +4 immunity: the best boots you can buy'},
 {name:'Glow Ring',cat:'Gear',from:'Reward',unlock:'Night Fishing bundle',use:'Light around you in the mines; slimes on floor 40+ drop it too'},
 {name:'Small Magnet Ring',cat:'Gear',from:'Reward',unlock:'Adventurer’s bundle',use:'Pulls drops toward you from a tile further'},
 {name:'Topaz Ring',cat:'Gear',from:'Marlon',gold:1000,use:'+1 defence'},
 {name:'Aquamarine Ring',cat:'Gear',from:'Marlon',gold:2500,unlock:'floor 40',use:'+10% critical hit chance'},
 {name:'Ruby Ring',cat:'Gear',from:'Marlon',gold:5000,unlock:'floor 80',use:'+10% attack'},
 {name:'Vampire Ring',cat:'Gear',from:'Marlon',unlock:'200 bats killed',use:'+2 health per kill: the ring for floors 80 to 120'},
 {name:'Burglar’s Ring',cat:'Gear',from:'Marlon',unlock:'500 Dust Sprites killed',use:'Monsters drop more: doubles the coal from sprite farming'}
];
