/* Farmhand's Route - offline service worker. Generated by tools/make_sw.py; do not edit by hand. */
var VERSION = 'fr-20260919-225600';
var FONTS = 'fr-fonts';
var PRECACHE = ["./", "index.html", "manifest.webmanifest", "art/sheet.png", "art/icon-192.png", "art/icon-512.png", "art/icon-512-maskable.png", "art/apple-touch-icon.png", "js/data.js?v=11", "js/bundles.js?v=11", "js/legend.js?v=11", "js/items.js?v=11", "js/perfection.js?v=11", "js/people.js?v=11", "js/art.js?v=11", "js/app.js?v=11"];

/* install: fetch the whole app into a versioned cache, then take over without waiting */
self.addEventListener('install', function(e){
  e.waitUntil(caches.open(VERSION).then(function(c){ return c.addAll(PRECACHE); }).then(function(){ return self.skipWaiting(); }));
});
/* activate: drop every older app cache (the font cache is shared across versions) */
self.addEventListener('activate', function(e){
  e.waitUntil(caches.keys().then(function(keys){
    return Promise.all(keys.filter(function(k){ return k !== VERSION && k !== FONTS; }).map(function(k){ return caches.delete(k); }));
  }).then(function(){ return self.clients.claim(); }));
});
/* fetch: the app itself is cache first; a navigation that misses falls back to index.html; fonts are cached as they arrive */
self.addEventListener('fetch', function(e){
  var req = e.request; if(req.method !== 'GET') return;
  var url = new URL(req.url);
  if(url.origin === location.origin){
    e.respondWith(caches.match(req).then(function(hit){
      if(hit) return hit;
      return fetch(req).catch(function(){ if(req.mode === 'navigate') return caches.match('index.html'); });
    }));
    return;
  }
  if(url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com'){
    e.respondWith(caches.open(FONTS).then(function(c){
      return c.match(req).then(function(hit){
        var net = fetch(req).then(function(res){ if(res && res.ok) c.put(req, res.clone()); return res; }).catch(function(){ return hit; });
        return hit || net;
      });
    }));
  }
});
