"""Generate sw.js, the offline service worker, from the script tags in index.html.
Run after any change that should reach installed phones, then commit and push:
    python tools/make_sw.py
Every run stamps a new version, so installed copies fetch the new files on their next open.
"""
import os, re, time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXED = ['./', 'index.html', 'manifest.webmanifest', 'art/sheet.png', 'art/icon-192.png', 'art/icon-512.png', 'art/icon-512-maskable.png', 'art/apple-touch-icon.png']

def main():
    html = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()
    scripts = re.findall(r'<script src="(js/[^"]+)"', html)
    assert scripts, 'no script tags found in index.html'
    files = FIXED + scripts
    for f in files:
        p = f.split('?')[0]
        if p != './':
            assert os.path.exists(os.path.join(ROOT, p)), 'missing ' + p
    version = 'fr-' + time.strftime('%Y%m%d-%H%M%S')
    body = "/* Farmhand's Route - offline service worker. Generated by tools/make_sw.py; do not edit by hand. */\n"
    body += "var VERSION = '" + version + "';\n"
    body += "var FONTS = 'fr-fonts';\n"
    body += "var PRECACHE = " + repr(files).replace("'", '"') + ";\n"
    body += r"""
/* install: fetch the whole app into a versioned cache, then take over without waiting */
self.addEventListener('install', function(e){
  e.waitUntil(caches.open(VERSION).then(function(c){ return c.addAll(PRECACHE); }).then(function(){ return self.skipWaiting(); }));
});
/* activate: drop every older app cache (the font cache is shared across versions) */
self.addEventListener('activate', function(e){
  e.waitUntil(caches.keys().then(function(keys){
    return Promise.all(keys.filter(function(k){ return k !== VERSION && k !== FONTS; }).map(function(k){ return caches.delete(k); }));
  }).then(function(){ return self.clients.claim(); }));
});
/* fetch: the app itself is cache first; a navigation that misses falls back to index.html; fonts are cached as they arrive */
self.addEventListener('fetch', function(e){
  var req = e.request; if(req.method !== 'GET') return;
  var url = new URL(req.url);
  if(url.origin === location.origin){
    e.respondWith(caches.match(req).then(function(hit){
      if(hit) return hit;
      return fetch(req).catch(function(){ if(req.mode === 'navigate') return caches.match('index.html'); });
    }));
    return;
  }
  if(url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com'){
    e.respondWith(caches.open(FONTS).then(function(c){
      return c.match(req).then(function(hit){
        var net = fetch(req).then(function(res){ if(res && res.ok) c.put(req, res.clone()); return res; }).catch(function(){ return hit; });
        return hit || net;
      });
    }));
  }
});
"""
    out = os.path.join(ROOT, 'sw.js')
    tmp = out + '.tmp.js'
    open(tmp, 'wb').write(body.encode('utf-8'))
    import subprocess
    r = subprocess.run(['node', '--check', tmp], capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stderr); raise SystemExit(1)
    os.replace(tmp, out)
    print('sw.js', version, len(files), 'files')

if __name__ == '__main__':
    main()
